### ISSUE TITLE
Update text to reflect Styled-Component  "composition" support

### ISSUE THREAD

**Issue by JuanmaMenendez** [jjprevite/styled-components-vs-emotion#4]
In the text you mention: "In addition, classNames used in emotion are powerful because the css API has a special property called composes that allows you to create new styles composed with previously created styles"

With Styled-Components that is possible as well. please see: https://www.styled-components.com/docs/advanced#referring-to-other-components

**Comment by jsjoeio** [comment]
@JuanmaMenendez thanks for pointing that out! Feel free to submit a PR to update this section :)

**Comment by JuanmaMenendez** [comment]
Would just add **Composition** to the Comparision Table, put **yes** in both and remove the **Emotion** composition example.

Here you can see a live example of composition with Styled Components https://codesandbox.io/s/6zr1ropj23

**Comment by jsjoeio** [comment]
Awesome! Glad to hear it's not a lot to add 

Feel free to update and submit a PR 😄 I'm guessing it'll take you 2 mins!

**Comment by JuanmaMenendez** [comment]
Done. Please check my PR https://github.com/jsjoeio/styled-components-vs-emotion/pull/5

**Comment by jsjoeio** [comment]
You rock! Thank you again :)
